# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://algotrade.exchange
title: AlgoTrade Exchange
email: gianluca.ciocci@gmail.com
author: Gianluca Ciocci
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/GianlucaCiocci
  - title: github
    url: https://github.com/AlgoTrade
  - title: linkedin
    url: http://uk.linkedin.com/in/gianlucaciocci
